static const CPUOpcode s_opcodes[256] = {
  /* $00 */ { CPUInstKind::BRK, CPUAddrMode::Imm, 7 },
  /* $01 */ { CPUInstKind::ORA, CPUAddrMode::X_Ind, 6 },
  /* $02 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $03 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $04 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $05 */ { CPUInstKind::ORA, CPUAddrMode::Zpg, 3 },
  /* $06 */ { CPUInstKind::ASL, CPUAddrMode::Zpg, 5 },
  /* $07 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $08 */ { CPUInstKind::PHP, CPUAddrMode::Implied, 3 },
  /* $09 */ { CPUInstKind::ORA, CPUAddrMode::Imm, 2 },
  /* $0A */ { CPUInstKind::ASL, CPUAddrMode::A, 2 },
  /* $0B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $0C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $0D */ { CPUInstKind::ORA, CPUAddrMode::Abs, 4 },
  /* $0E */ { CPUInstKind::ASL, CPUAddrMode::Abs, 6 },
  /* $0F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $10 */ { CPUInstKind::BPL, CPUAddrMode::Rel, 2 },
  /* $11 */ { CPUInstKind::ORA, CPUAddrMode::Ind_Y, 5 },
  /* $12 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $13 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $14 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $15 */ { CPUInstKind::ORA, CPUAddrMode::Zpg_X, 4 },
  /* $16 */ { CPUInstKind::ASL, CPUAddrMode::Zpg_X, 6 },
  /* $17 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $18 */ { CPUInstKind::CLC, CPUAddrMode::Implied, 2 },
  /* $19 */ { CPUInstKind::ORA, CPUAddrMode::Abs_Y, 4 },
  /* $1A */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $1B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $1C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $1D */ { CPUInstKind::ORA, CPUAddrMode::Abs_X, 4 },
  /* $1E */ { CPUInstKind::ASL, CPUAddrMode::Abs_X, 7 },
  /* $1F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $20 */ { CPUInstKind::JSR, CPUAddrMode::Abs, 6 },
  /* $21 */ { CPUInstKind::AND, CPUAddrMode::X_Ind, 6 },
  /* $22 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $23 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $24 */ { CPUInstKind::BIT, CPUAddrMode::Zpg, 3 },
  /* $25 */ { CPUInstKind::AND, CPUAddrMode::Zpg, 3 },
  /* $26 */ { CPUInstKind::ROL, CPUAddrMode::Zpg, 5 },
  /* $27 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $28 */ { CPUInstKind::PLP, CPUAddrMode::Implied, 4 },
  /* $29 */ { CPUInstKind::AND, CPUAddrMode::Imm, 2 },
  /* $2A */ { CPUInstKind::ROL, CPUAddrMode::A, 2 },
  /* $2B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $2C */ { CPUInstKind::BIT, CPUAddrMode::Abs, 4 },
  /* $2D */ { CPUInstKind::AND, CPUAddrMode::Abs, 4 },
  /* $2E */ { CPUInstKind::ROL, CPUAddrMode::Abs, 6 },
  /* $2F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $30 */ { CPUInstKind::BMI, CPUAddrMode::Rel, 2 },
  /* $31 */ { CPUInstKind::AND, CPUAddrMode::Ind_Y, 5 },
  /* $32 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $33 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $34 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $35 */ { CPUInstKind::AND, CPUAddrMode::Zpg_X, 4 },
  /* $36 */ { CPUInstKind::ROL, CPUAddrMode::Zpg_X, 6 },
  /* $37 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $38 */ { CPUInstKind::SEC, CPUAddrMode::Implied, 2 },
  /* $39 */ { CPUInstKind::AND, CPUAddrMode::Abs_Y, 4 },
  /* $3A */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $3B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $3C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $3D */ { CPUInstKind::AND, CPUAddrMode::Abs_X, 4 },
  /* $3E */ { CPUInstKind::ROL, CPUAddrMode::Abs_X, 7 },
  /* $3F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $40 */ { CPUInstKind::RTI, CPUAddrMode::Implied, 6 },
  /* $41 */ { CPUInstKind::EOR, CPUAddrMode::X_Ind, 6 },
  /* $42 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $43 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $44 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $45 */ { CPUInstKind::EOR, CPUAddrMode::Zpg, 3 },
  /* $46 */ { CPUInstKind::LSR, CPUAddrMode::Zpg, 5 },
  /* $47 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $48 */ { CPUInstKind::PHA, CPUAddrMode::Implied, 3 },
  /* $49 */ { CPUInstKind::EOR, CPUAddrMode::Imm, 2 },
  /* $4A */ { CPUInstKind::LSR, CPUAddrMode::A, 2 },
  /* $4B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $4C */ { CPUInstKind::JMP, CPUAddrMode::Abs, 3 },
  /* $4D */ { CPUInstKind::EOR, CPUAddrMode::Abs, 4 },
  /* $4E */ { CPUInstKind::LSR, CPUAddrMode::Abs, 6 },
  /* $4F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $50 */ { CPUInstKind::BVC, CPUAddrMode::Rel, 2 },
  /* $51 */ { CPUInstKind::EOR, CPUAddrMode::Ind_Y, 5 },
  /* $52 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $53 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $54 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $55 */ { CPUInstKind::EOR, CPUAddrMode::Zpg_X, 4 },
  /* $56 */ { CPUInstKind::LSR, CPUAddrMode::Zpg_X, 6 },
  /* $57 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $58 */ { CPUInstKind::CLI, CPUAddrMode::Implied, 2 },
  /* $59 */ { CPUInstKind::EOR, CPUAddrMode::Abs_Y, 4 },
  /* $5A */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $5B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $5C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $5D */ { CPUInstKind::EOR, CPUAddrMode::Abs_X, 4 },
  /* $5E */ { CPUInstKind::LSR, CPUAddrMode::Abs_X, 7 },
  /* $5F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $60 */ { CPUInstKind::RTS, CPUAddrMode::Implied, 6 },
  /* $61 */ { CPUInstKind::ADC, CPUAddrMode::X_Ind, 6 },
  /* $62 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $63 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $64 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $65 */ { CPUInstKind::ADC, CPUAddrMode::Zpg, 3 },
  /* $66 */ { CPUInstKind::ROR, CPUAddrMode::Zpg, 5 },
  /* $67 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $68 */ { CPUInstKind::PLA, CPUAddrMode::Implied, 4 },
  /* $69 */ { CPUInstKind::ADC, CPUAddrMode::Imm, 2 },
  /* $6A */ { CPUInstKind::ROR, CPUAddrMode::A, 2 },
  /* $6B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $6C */ { CPUInstKind::JMP, CPUAddrMode::Ind, 5 },
  /* $6D */ { CPUInstKind::ADC, CPUAddrMode::Abs, 4 },
  /* $6E */ { CPUInstKind::ROR, CPUAddrMode::Abs, 6 },
  /* $6F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $70 */ { CPUInstKind::BVS, CPUAddrMode::Rel, 2 },
  /* $71 */ { CPUInstKind::ADC, CPUAddrMode::Ind_Y, 5 },
  /* $72 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $73 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $74 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $75 */ { CPUInstKind::ADC, CPUAddrMode::Zpg_X, 4 },
  /* $76 */ { CPUInstKind::ROR, CPUAddrMode::Zpg_X, 6 },
  /* $77 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $78 */ { CPUInstKind::SEI, CPUAddrMode::Implied, 2 },
  /* $79 */ { CPUInstKind::ADC, CPUAddrMode::Abs_Y, 4 },
  /* $7A */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $7B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $7C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $7D */ { CPUInstKind::ADC, CPUAddrMode::Abs_X, 4 },
  /* $7E */ { CPUInstKind::ROR, CPUAddrMode::Abs_X, 7 },
  /* $7F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $80 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $81 */ { CPUInstKind::STA, CPUAddrMode::X_Ind, 6 },
  /* $82 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $83 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $84 */ { CPUInstKind::STY, CPUAddrMode::Zpg, 3 },
  /* $85 */ { CPUInstKind::STA, CPUAddrMode::Zpg, 3 },
  /* $86 */ { CPUInstKind::STX, CPUAddrMode::Zpg, 3 },
  /* $87 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $88 */ { CPUInstKind::DEY, CPUAddrMode::Implied, 2 },
  /* $89 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $8A */ { CPUInstKind::TXA, CPUAddrMode::Implied, 2 },
  /* $8B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $8C */ { CPUInstKind::STY, CPUAddrMode::Abs, 4 },
  /* $8D */ { CPUInstKind::STA, CPUAddrMode::Abs, 4 },
  /* $8E */ { CPUInstKind::STX, CPUAddrMode::Abs, 4 },
  /* $8F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $90 */ { CPUInstKind::BCC, CPUAddrMode::Rel, 2 },
  /* $91 */ { CPUInstKind::STA, CPUAddrMode::Ind_Y, 6 },
  /* $92 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $93 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $94 */ { CPUInstKind::STY, CPUAddrMode::Zpg_X, 4 },
  /* $95 */ { CPUInstKind::STA, CPUAddrMode::Zpg_X, 4 },
  /* $96 */ { CPUInstKind::STX, CPUAddrMode::Zpg_Y, 4 },
  /* $97 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $98 */ { CPUInstKind::TYA, CPUAddrMode::Implied, 2 },
  /* $99 */ { CPUInstKind::STA, CPUAddrMode::Abs_Y, 5 },
  /* $9A */ { CPUInstKind::TXS, CPUAddrMode::Implied, 2 },
  /* $9B */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $9C */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $9D */ { CPUInstKind::STA, CPUAddrMode::Abs_X, 5 },
  /* $9E */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $9F */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $A0 */ { CPUInstKind::LDY, CPUAddrMode::Imm, 2 },
  /* $A1 */ { CPUInstKind::LDA, CPUAddrMode::X_Ind, 6 },
  /* $A2 */ { CPUInstKind::LDX, CPUAddrMode::Imm, 2 },
  /* $A3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $A4 */ { CPUInstKind::LDY, CPUAddrMode::Zpg, 3 },
  /* $A5 */ { CPUInstKind::LDA, CPUAddrMode::Zpg, 3 },
  /* $A6 */ { CPUInstKind::LDX, CPUAddrMode::Zpg, 3 },
  /* $A7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $A8 */ { CPUInstKind::TAY, CPUAddrMode::Implied, 2 },
  /* $A9 */ { CPUInstKind::LDA, CPUAddrMode::Imm, 2 },
  /* $AA */ { CPUInstKind::TAX, CPUAddrMode::Implied, 2 },
  /* $AB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $AC */ { CPUInstKind::LDY, CPUAddrMode::Abs, 4 },
  /* $AD */ { CPUInstKind::LDA, CPUAddrMode::Abs, 4 },
  /* $AE */ { CPUInstKind::LDX, CPUAddrMode::Abs, 4 },
  /* $AF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $B0 */ { CPUInstKind::BCS, CPUAddrMode::Rel, 2 },
  /* $B1 */ { CPUInstKind::LDA, CPUAddrMode::Ind_Y, 5 },
  /* $B2 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $B3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $B4 */ { CPUInstKind::LDY, CPUAddrMode::Zpg_X, 4 },
  /* $B5 */ { CPUInstKind::LDA, CPUAddrMode::Zpg_X, 4 },
  /* $B6 */ { CPUInstKind::LDX, CPUAddrMode::Zpg_Y, 4 },
  /* $B7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $B8 */ { CPUInstKind::CLV, CPUAddrMode::Implied, 2 },
  /* $B9 */ { CPUInstKind::LDA, CPUAddrMode::Abs_Y, 4 },
  /* $BA */ { CPUInstKind::TSX, CPUAddrMode::Implied, 2 },
  /* $BB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $BC */ { CPUInstKind::LDY, CPUAddrMode::Abs_X, 4 },
  /* $BD */ { CPUInstKind::LDA, CPUAddrMode::Abs_X, 4 },
  /* $BE */ { CPUInstKind::LDX, CPUAddrMode::Abs_Y, 4 },
  /* $BF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $C0 */ { CPUInstKind::CPY, CPUAddrMode::Imm, 2 },
  /* $C1 */ { CPUInstKind::CMP, CPUAddrMode::X_Ind, 6 },
  /* $C2 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $C3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $C4 */ { CPUInstKind::CPY, CPUAddrMode::Zpg, 3 },
  /* $C5 */ { CPUInstKind::CMP, CPUAddrMode::Zpg, 3 },
  /* $C6 */ { CPUInstKind::DEC, CPUAddrMode::Zpg, 5 },
  /* $C7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $C8 */ { CPUInstKind::INY, CPUAddrMode::Implied, 2 },
  /* $C9 */ { CPUInstKind::CMP, CPUAddrMode::Imm, 2 },
  /* $CA */ { CPUInstKind::DEX, CPUAddrMode::Implied, 2 },
  /* $CB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $CC */ { CPUInstKind::CPY, CPUAddrMode::Abs, 4 },
  /* $CD */ { CPUInstKind::CMP, CPUAddrMode::Abs, 4 },
  /* $CE */ { CPUInstKind::DEC, CPUAddrMode::Abs, 6 },
  /* $CF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $D0 */ { CPUInstKind::BNE, CPUAddrMode::Rel, 2 },
  /* $D1 */ { CPUInstKind::CMP, CPUAddrMode::Ind_Y, 5 },
  /* $D2 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $D3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $D4 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $D5 */ { CPUInstKind::CMP, CPUAddrMode::Zpg_X, 4 },
  /* $D6 */ { CPUInstKind::DEC, CPUAddrMode::Zpg_X, 6 },
  /* $D7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $D8 */ { CPUInstKind::CLD, CPUAddrMode::Implied, 2 },
  /* $D9 */ { CPUInstKind::CMP, CPUAddrMode::Abs_Y, 4 },
  /* $DA */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $DB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $DC */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $DD */ { CPUInstKind::CMP, CPUAddrMode::Abs_X, 4 },
  /* $DE */ { CPUInstKind::DEC, CPUAddrMode::Abs_X, 7 },
  /* $DF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $E0 */ { CPUInstKind::CPX, CPUAddrMode::Imm, 2 },
  /* $E1 */ { CPUInstKind::SBC, CPUAddrMode::X_Ind, 6 },
  /* $E2 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $E3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $E4 */ { CPUInstKind::CPX, CPUAddrMode::Zpg, 3 },
  /* $E5 */ { CPUInstKind::SBC, CPUAddrMode::Zpg, 3 },
  /* $E6 */ { CPUInstKind::INC, CPUAddrMode::Zpg, 5 },
  /* $E7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $E8 */ { CPUInstKind::INX, CPUAddrMode::Implied, 2 },
  /* $E9 */ { CPUInstKind::SBC, CPUAddrMode::Imm, 2 },
  /* $EA */ { CPUInstKind::NOP, CPUAddrMode::Implied, 2 },
  /* $EB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $EC */ { CPUInstKind::CPX, CPUAddrMode::Abs, 4 },
  /* $ED */ { CPUInstKind::SBC, CPUAddrMode::Abs, 4 },
  /* $EE */ { CPUInstKind::INC, CPUAddrMode::Abs, 6 },
  /* $EF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $F0 */ { CPUInstKind::BEQ, CPUAddrMode::Rel, 2 },
  /* $F1 */ { CPUInstKind::SBC, CPUAddrMode::Ind_Y, 5 },
  /* $F2 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $F3 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $F4 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $F5 */ { CPUInstKind::SBC, CPUAddrMode::Zpg_X, 4 },
  /* $F6 */ { CPUInstKind::INC, CPUAddrMode::Zpg_X, 6 },
  /* $F7 */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $F8 */ { CPUInstKind::SED, CPUAddrMode::Implied, 2 },
  /* $F9 */ { CPUInstKind::SBC, CPUAddrMode::Abs_Y, 4 },
  /* $FA */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $FB */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $FC */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
  /* $FD */ { CPUInstKind::SBC, CPUAddrMode::Abs_X, 4 },
  /* $FE */ { CPUInstKind::INC, CPUAddrMode::Abs_X, 7 },
  /* $FF */ { CPUInstKind::INVALID, CPUAddrMode::_invalid, 0 },
};

static const AsmEncoding s_encodings[] = {
  { { CPUInstKind::ADC, CPUAddrMode::Abs, 4 }, 0x6D },
  { { CPUInstKind::ADC, CPUAddrMode::Abs_X, 4 }, 0x7D },
  { { CPUInstKind::ADC, CPUAddrMode::Abs_Y, 4 }, 0x79 },
  { { CPUInstKind::ADC, CPUAddrMode::Imm, 2 }, 0x69 },
  { { CPUInstKind::ADC, CPUAddrMode::X_Ind, 6 }, 0x61 },
  { { CPUInstKind::ADC, CPUAddrMode::Ind_Y, 5 }, 0x71 },
  { { CPUInstKind::ADC, CPUAddrMode::Zpg, 3 }, 0x65 },
  { { CPUInstKind::ADC, CPUAddrMode::Zpg_X, 4 }, 0x75 },
  { { CPUInstKind::AND, CPUAddrMode::Abs, 4 }, 0x2D },
  { { CPUInstKind::AND, CPUAddrMode::Abs_X, 4 }, 0x3D },
  { { CPUInstKind::AND, CPUAddrMode::Abs_Y, 4 }, 0x39 },
  { { CPUInstKind::AND, CPUAddrMode::Imm, 2 }, 0x29 },
  { { CPUInstKind::AND, CPUAddrMode::X_Ind, 6 }, 0x21 },
  { { CPUInstKind::AND, CPUAddrMode::Ind_Y, 5 }, 0x31 },
  { { CPUInstKind::AND, CPUAddrMode::Zpg, 3 }, 0x25 },
  { { CPUInstKind::AND, CPUAddrMode::Zpg_X, 4 }, 0x35 },
  { { CPUInstKind::ASL, CPUAddrMode::A, 2 }, 0x0A },
  { { CPUInstKind::ASL, CPUAddrMode::Abs, 6 }, 0x0E },
  { { CPUInstKind::ASL, CPUAddrMode::Abs_X, 7 }, 0x1E },
  { { CPUInstKind::ASL, CPUAddrMode::Zpg, 5 }, 0x06 },
  { { CPUInstKind::ASL, CPUAddrMode::Zpg_X, 6 }, 0x16 },
  { { CPUInstKind::BCC, CPUAddrMode::Rel, 2 }, 0x90 },
  { { CPUInstKind::BCS, CPUAddrMode::Rel, 2 }, 0xB0 },
  { { CPUInstKind::BEQ, CPUAddrMode::Rel, 2 }, 0xF0 },
  { { CPUInstKind::BIT, CPUAddrMode::Abs, 4 }, 0x2C },
  { { CPUInstKind::BIT, CPUAddrMode::Zpg, 3 }, 0x24 },
  { { CPUInstKind::BMI, CPUAddrMode::Rel, 2 }, 0x30 },
  { { CPUInstKind::BNE, CPUAddrMode::Rel, 2 }, 0xD0 },
  { { CPUInstKind::BPL, CPUAddrMode::Rel, 2 }, 0x10 },
  { { CPUInstKind::BRK, CPUAddrMode::Imm, 7 }, 0x00 },
  { { CPUInstKind::BVC, CPUAddrMode::Rel, 2 }, 0x50 },
  { { CPUInstKind::BVS, CPUAddrMode::Rel, 2 }, 0x70 },
  { { CPUInstKind::CLC, CPUAddrMode::Implied, 2 }, 0x18 },
  { { CPUInstKind::CLD, CPUAddrMode::Implied, 2 }, 0xD8 },
  { { CPUInstKind::CLI, CPUAddrMode::Implied, 2 }, 0x58 },
  { { CPUInstKind::CLV, CPUAddrMode::Implied, 2 }, 0xB8 },
  { { CPUInstKind::CMP, CPUAddrMode::Abs, 4 }, 0xCD },
  { { CPUInstKind::CMP, CPUAddrMode::Abs_X, 4 }, 0xDD },
  { { CPUInstKind::CMP, CPUAddrMode::Abs_Y, 4 }, 0xD9 },
  { { CPUInstKind::CMP, CPUAddrMode::Imm, 2 }, 0xC9 },
  { { CPUInstKind::CMP, CPUAddrMode::X_Ind, 6 }, 0xC1 },
  { { CPUInstKind::CMP, CPUAddrMode::Ind_Y, 5 }, 0xD1 },
  { { CPUInstKind::CMP, CPUAddrMode::Zpg, 3 }, 0xC5 },
  { { CPUInstKind::CMP, CPUAddrMode::Zpg_X, 4 }, 0xD5 },
  { { CPUInstKind::CPX, CPUAddrMode::Abs, 4 }, 0xEC },
  { { CPUInstKind::CPX, CPUAddrMode::Imm, 2 }, 0xE0 },
  { { CPUInstKind::CPX, CPUAddrMode::Zpg, 3 }, 0xE4 },
  { { CPUInstKind::CPY, CPUAddrMode::Abs, 4 }, 0xCC },
  { { CPUInstKind::CPY, CPUAddrMode::Imm, 2 }, 0xC0 },
  { { CPUInstKind::CPY, CPUAddrMode::Zpg, 3 }, 0xC4 },
  { { CPUInstKind::DEC, CPUAddrMode::Abs, 6 }, 0xCE },
  { { CPUInstKind::DEC, CPUAddrMode::Abs_X, 7 }, 0xDE },
  { { CPUInstKind::DEC, CPUAddrMode::Zpg, 5 }, 0xC6 },
  { { CPUInstKind::DEC, CPUAddrMode::Zpg_X, 6 }, 0xD6 },
  { { CPUInstKind::DEX, CPUAddrMode::Implied, 2 }, 0xCA },
  { { CPUInstKind::DEY, CPUAddrMode::Implied, 2 }, 0x88 },
  { { CPUInstKind::EOR, CPUAddrMode::Abs, 4 }, 0x4D },
  { { CPUInstKind::EOR, CPUAddrMode::Abs_X, 4 }, 0x5D },
  { { CPUInstKind::EOR, CPUAddrMode::Abs_Y, 4 }, 0x59 },
  { { CPUInstKind::EOR, CPUAddrMode::Imm, 2 }, 0x49 },
  { { CPUInstKind::EOR, CPUAddrMode::X_Ind, 6 }, 0x41 },
  { { CPUInstKind::EOR, CPUAddrMode::Ind_Y, 5 }, 0x51 },
  { { CPUInstKind::EOR, CPUAddrMode::Zpg, 3 }, 0x45 },
  { { CPUInstKind::EOR, CPUAddrMode::Zpg_X, 4 }, 0x55 },
  { { CPUInstKind::INC, CPUAddrMode::Abs, 6 }, 0xEE },
  { { CPUInstKind::INC, CPUAddrMode::Abs_X, 7 }, 0xFE },
  { { CPUInstKind::INC, CPUAddrMode::Zpg, 5 }, 0xE6 },
  { { CPUInstKind::INC, CPUAddrMode::Zpg_X, 6 }, 0xF6 },
  { { CPUInstKind::INX, CPUAddrMode::Implied, 2 }, 0xE8 },
  { { CPUInstKind::INY, CPUAddrMode::Implied, 2 }, 0xC8 },
  { { CPUInstKind::JMP, CPUAddrMode::Abs, 3 }, 0x4C },
  { { CPUInstKind::JMP, CPUAddrMode::Ind, 5 }, 0x6C },
  { { CPUInstKind::JSR, CPUAddrMode::Abs, 6 }, 0x20 },
  { { CPUInstKind::LDA, CPUAddrMode::Abs, 4 }, 0xAD },
  { { CPUInstKind::LDA, CPUAddrMode::Abs_X, 4 }, 0xBD },
  { { CPUInstKind::LDA, CPUAddrMode::Abs_Y, 4 }, 0xB9 },
  { { CPUInstKind::LDA, CPUAddrMode::Imm, 2 }, 0xA9 },
  { { CPUInstKind::LDA, CPUAddrMode::X_Ind, 6 }, 0xA1 },
  { { CPUInstKind::LDA, CPUAddrMode::Ind_Y, 5 }, 0xB1 },
  { { CPUInstKind::LDA, CPUAddrMode::Zpg, 3 }, 0xA5 },
  { { CPUInstKind::LDA, CPUAddrMode::Zpg_X, 4 }, 0xB5 },
  { { CPUInstKind::LDX, CPUAddrMode::Abs, 4 }, 0xAE },
  { { CPUInstKind::LDX, CPUAddrMode::Abs_Y, 4 }, 0xBE },
  { { CPUInstKind::LDX, CPUAddrMode::Imm, 2 }, 0xA2 },
  { { CPUInstKind::LDX, CPUAddrMode::Zpg, 3 }, 0xA6 },
  { { CPUInstKind::LDX, CPUAddrMode::Zpg_Y, 4 }, 0xB6 },
  { { CPUInstKind::LDY, CPUAddrMode::Abs, 4 }, 0xAC },
  { { CPUInstKind::LDY, CPUAddrMode::Abs_X, 4 }, 0xBC },
  { { CPUInstKind::LDY, CPUAddrMode::Imm, 2 }, 0xA0 },
  { { CPUInstKind::LDY, CPUAddrMode::Zpg, 3 }, 0xA4 },
  { { CPUInstKind::LDY, CPUAddrMode::Zpg_X, 4 }, 0xB4 },
  { { CPUInstKind::LSR, CPUAddrMode::A, 2 }, 0x4A },
  { { CPUInstKind::LSR, CPUAddrMode::Abs, 6 }, 0x4E },
  { { CPUInstKind::LSR, CPUAddrMode::Abs_X, 7 }, 0x5E },
  { { CPUInstKind::LSR, CPUAddrMode::Zpg, 5 }, 0x46 },
  { { CPUInstKind::LSR, CPUAddrMode::Zpg_X, 6 }, 0x56 },
  { { CPUInstKind::NOP, CPUAddrMode::Implied, 2 }, 0xEA },
  { { CPUInstKind::ORA, CPUAddrMode::Abs, 4 }, 0x0D },
  { { CPUInstKind::ORA, CPUAddrMode::Abs_X, 4 }, 0x1D },
  { { CPUInstKind::ORA, CPUAddrMode::Abs_Y, 4 }, 0x19 },
  { { CPUInstKind::ORA, CPUAddrMode::Imm, 2 }, 0x09 },
  { { CPUInstKind::ORA, CPUAddrMode::X_Ind, 6 }, 0x01 },
  { { CPUInstKind::ORA, CPUAddrMode::Ind_Y, 5 }, 0x11 },
  { { CPUInstKind::ORA, CPUAddrMode::Zpg, 3 }, 0x05 },
  { { CPUInstKind::ORA, CPUAddrMode::Zpg_X, 4 }, 0x15 },
  { { CPUInstKind::PHA, CPUAddrMode::Implied, 3 }, 0x48 },
  { { CPUInstKind::PHP, CPUAddrMode::Implied, 3 }, 0x08 },
  { { CPUInstKind::PLA, CPUAddrMode::Implied, 4 }, 0x68 },
  { { CPUInstKind::PLP, CPUAddrMode::Implied, 4 }, 0x28 },
  { { CPUInstKind::ROL, CPUAddrMode::A, 2 }, 0x2A },
  { { CPUInstKind::ROL, CPUAddrMode::Abs, 6 }, 0x2E },
  { { CPUInstKind::ROL, CPUAddrMode::Abs_X, 7 }, 0x3E },
  { { CPUInstKind::ROL, CPUAddrMode::Zpg, 5 }, 0x26 },
  { { CPUInstKind::ROL, CPUAddrMode::Zpg_X, 6 }, 0x36 },
  { { CPUInstKind::ROR, CPUAddrMode::A, 2 }, 0x6A },
  { { CPUInstKind::ROR, CPUAddrMode::Abs, 6 }, 0x6E },
  { { CPUInstKind::ROR, CPUAddrMode::Abs_X, 7 }, 0x7E },
  { { CPUInstKind::ROR, CPUAddrMode::Zpg, 5 }, 0x66 },
  { { CPUInstKind::ROR, CPUAddrMode::Zpg_X, 6 }, 0x76 },
  { { CPUInstKind::RTI, CPUAddrMode::Implied, 6 }, 0x40 },
  { { CPUInstKind::RTS, CPUAddrMode::Implied, 6 }, 0x60 },
  { { CPUInstKind::SBC, CPUAddrMode::Abs, 4 }, 0xED },
  { { CPUInstKind::SBC, CPUAddrMode::Abs_X, 4 }, 0xFD },
  { { CPUInstKind::SBC, CPUAddrMode::Abs_Y, 4 }, 0xF9 },
  { { CPUInstKind::SBC, CPUAddrMode::Imm, 2 }, 0xE9 },
  { { CPUInstKind::SBC, CPUAddrMode::X_Ind, 6 }, 0xE1 },
  { { CPUInstKind::SBC, CPUAddrMode::Ind_Y, 5 }, 0xF1 },
  { { CPUInstKind::SBC, CPUAddrMode::Zpg, 3 }, 0xE5 },
  { { CPUInstKind::SBC, CPUAddrMode::Zpg_X, 4 }, 0xF5 },
  { { CPUInstKind::SEC, CPUAddrMode::Implied, 2 }, 0x38 },
  { { CPUInstKind::SED, CPUAddrMode::Implied, 2 }, 0xF8 },
  { { CPUInstKind::SEI, CPUAddrMode::Implied, 2 }, 0x78 },
  { { CPUInstKind::STA, CPUAddrMode::Abs, 4 }, 0x8D },
  { { CPUInstKind::STA, CPUAddrMode::Abs_X, 5 }, 0x9D },
  { { CPUInstKind::STA, CPUAddrMode::Abs_Y, 5 }, 0x99 },
  { { CPUInstKind::STA, CPUAddrMode::X_Ind, 6 }, 0x81 },
  { { CPUInstKind::STA, CPUAddrMode::Ind_Y, 6 }, 0x91 },
  { { CPUInstKind::STA, CPUAddrMode::Zpg, 3 }, 0x85 },
  { { CPUInstKind::STA, CPUAddrMode::Zpg_X, 4 }, 0x95 },
  { { CPUInstKind::STX, CPUAddrMode::Abs, 4 }, 0x8E },
  { { CPUInstKind::STX, CPUAddrMode::Zpg, 3 }, 0x86 },
  { { CPUInstKind::STX, CPUAddrMode::Zpg_Y, 4 }, 0x96 },
  { { CPUInstKind::STY, CPUAddrMode::Abs, 4 }, 0x8C },
  { { CPUInstKind::STY, CPUAddrMode::Zpg, 3 }, 0x84 },
  { { CPUInstKind::STY, CPUAddrMode::Zpg_X, 4 }, 0x94 },
  { { CPUInstKind::TAX, CPUAddrMode::Implied, 2 }, 0xAA },
  { { CPUInstKind::TAY, CPUAddrMode::Implied, 2 }, 0xA8 },
  { { CPUInstKind::TSX, CPUAddrMode::Implied, 2 }, 0xBA },
  { { CPUInstKind::TXA, CPUAddrMode::Implied, 2 }, 0x8A },
  { { CPUInstKind::TXS, CPUAddrMode::Implied, 2 }, 0x9A },
  { { CPUInstKind::TYA, CPUAddrMode::Implied, 2 }, 0x98 },
};
static const unsigned s_encodings_len = 151;

static const char s_sortedNames[][4] = {
  "ADC",
  "AND",
  "ASL",
  "BCC",
  "BCS",
  "BEQ",
  "BIT",
  "BMI",
  "BNE",
  "BPL",
  "BRK",
  "BVC",
  "BVS",
  "CLC",
  "CLD",
  "CLI",
  "CLV",
  "CMP",
  "CPX",
  "CPY",
  "DEC",
  "DEX",
  "DEY",
  "EOR",
  "INC",
  "INX",
  "INY",
  "JMP",
  "JSR",
  "LDA",
  "LDX",
  "LDY",
  "LSR",
  "NOP",
  "ORA",
  "PHA",
  "PHP",
  "PLA",
  "PLP",
  "ROL",
  "ROR",
  "RTI",
  "RTS",
  "SBC",
  "SEC",
  "SED",
  "SEI",
  "STA",
  "STX",
  "STY",
  "TAX",
  "TAY",
  "TSX",
  "TXA",
  "TXS",
  "TYA",
};
static const CPUInstKind s_sortedNameKinds[] = {
  CPUInstKind::ADC,
  CPUInstKind::AND,
  CPUInstKind::ASL,
  CPUInstKind::BCC,
  CPUInstKind::BCS,
  CPUInstKind::BEQ,
  CPUInstKind::BIT,
  CPUInstKind::BMI,
  CPUInstKind::BNE,
  CPUInstKind::BPL,
  CPUInstKind::BRK,
  CPUInstKind::BVC,
  CPUInstKind::BVS,
  CPUInstKind::CLC,
  CPUInstKind::CLD,
  CPUInstKind::CLI,
  CPUInstKind::CLV,
  CPUInstKind::CMP,
  CPUInstKind::CPX,
  CPUInstKind::CPY,
  CPUInstKind::DEC,
  CPUInstKind::DEX,
  CPUInstKind::DEY,
  CPUInstKind::EOR,
  CPUInstKind::INC,
  CPUInstKind::INX,
  CPUInstKind::INY,
  CPUInstKind::JMP,
  CPUInstKind::JSR,
  CPUInstKind::LDA,
  CPUInstKind::LDX,
  CPUInstKind::LDY,
  CPUInstKind::LSR,
  CPUInstKind::NOP,
  CPUInstKind::ORA,
  CPUInstKind::PHA,
  CPUInstKind::PHP,
  CPUInstKind::PLA,
  CPUInstKind::PLP,
  CPUInstKind::ROL,
  CPUInstKind::ROR,
  CPUInstKind::RTI,
  CPUInstKind::RTS,
  CPUInstKind::SBC,
  CPUInstKind::SEC,
  CPUInstKind::SED,
  CPUInstKind::SEI,
  CPUInstKind::STA,
  CPUInstKind::STX,
  CPUInstKind::STY,
  CPUInstKind::TAX,
  CPUInstKind::TAY,
  CPUInstKind::TSX,
  CPUInstKind::TXA,
  CPUInstKind::TXS,
  CPUInstKind::TYA,
};
