#!/bin/bash
#
# Capture the machine state Snake Byte starts from, at $3750.
#
# Usage: make-entry-state.sh [build-dir]     (default ../../cmake-build-debug)
#
# Why not decoded/rom/boot-state.txt. That is the state at the BASIC prompt with
# nothing typed, and it is the right reference for what a boot produces in
# general. It is *not* what this game starts from: reaching $3750 means typing
# `CALL 14160`, and doing so leaves 74 bytes of difference in $0000-$07FF --
# Applesoft's parse state in zero page, its stack frames, the input buffer, and
# the echoed command on the text screen. Starting from the pristine state
# instead diverges on the very first screen sample.
#
# So this captures from snake-bytec1-ext-run itself, at its first arrival at
# $3750. That build boots and types the CALL, so it needs no key file.
#
# Everything outside $0000-$0802 is either the game image (already loaded), the
# ROM (likewise), or $FF -- verified below rather than assumed, because "the
# rest is $FF" is exactly the kind of claim that rots.

set -eu

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
bin=${1:-$here/../../cmake-build-debug}
prog=$bin/decoded/snake-byte/snake-bytec1-ext-run

[ -x "$prog" ] || { echo "$0: no snake-bytec1-ext-run at $prog" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

"$prog" --frames=400 --snapshot-at=3750 --snapshot-out="$tmp/entry.bin" > /dev/null 2>&1

od -An -tu1 -v "$tmp/entry.bin" | tr -s ' ' '\n' | grep -v '^$' > "$tmp/bytes"

# Assert the two gap regions really are uniform $FF before writing a header
# that says so. $3750-$854E is the game image and $D000-$FFFF the ROM; both are
# installed by the generated init_emulated().
awk '{ b[NR-1] = $1 }
     END {
       for (a = 2051; a < 14160; a++) if (b[a] != 255) bad++
       for (a = 34127; a < 49152; a++) if (b[a] != 255) bad++
       if (bad) { printf "%d bytes outside the header range are not 255\n", bad > "/dev/stderr"; exit 1 }
     }' "$tmp/bytes"

{
  echo "/* Generated by make-entry-state.sh. Do not edit. */"
  echo "/* Snake Byte's machine state at \$3750, captured from snake-bytec1-ext-run. */"
  echo "#pragma once"
  echo "#include <stdint.h>"
  echo ""
  echo "/* RAM \$0000-\$0802. Outside this: the game image, the ROM, and \$FF. */"
  echo "#define SB_ENTRY_RAM_LEN 0x803"
  echo "static const uint8_t kSnakeByteEntryRam[SB_ENTRY_RAM_LEN] = {"
  od -An -tu1 -v -N 2051 "$tmp/entry.bin" |
    awk '{ for (i = 1; i <= NF; i++) printf "%s%s,", (n++ % 16 == 0 ? "  " : " "), $i; print "" }'
  echo "};"
  echo ""
  awk '{ n = toupper($1); v = $2
         if (n == "A" || n == "X" || n == "Y" || n == "SP" || n == "STATUS")
           printf "#define SB_ENTRY_%s 0x%s\n", n, v
         else if (n == "VID_CONTROL")
           printf "#define SB_ENTRY_VID_CONTROL 0x%s\n", v }' "$tmp/entry.bin.regs"
} > "$here/entry-state-inc.h"

echo "wrote $here/entry-state-inc.h"
