/*
 * Copyright (c) Tzvetan Mikov.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/// \file
/// The translation unit that CMake actually compiles for the `snake-byte-easyc1-ext`
/// target.
///
/// This is the `easy` test fixture, built from snake-byte-easy.b33 -- the game
/// with its per-level apple quota lowered from 16 to 2 so that a recording can
/// reach level 2 and exercise the display-list interpreter. See make-easy.sh.
/// Everything below applies unchanged; only the generated file differs. It exists purely to stitch the generated code and the hand-written
/// ROM replacements into a single TU.
///
/// This is the *extern* variant. The plain `snake-bytec1` target is built from
/// the self-contained `snake-bytec1.c`, which decompiles the ROM along with the
/// game and links on its own; it is the reference build that `play.frames` was
/// recorded from, and the control this variant is checked against. Both are
/// generated by `decompile.sh` and both are verified by `verify.sh`.
///
/// Why a wrapper is necessary
/// --------------------------
/// `apple2tc/system2-inc.h` does not merely declare the emulated machine, it
/// *defines* it, and nearly all of it has internal linkage: the CPU registers
/// and flags (`s_a`, `s_x`, `s_y`, `s_sp`, `s_status_*`), the RAM array
/// (`s_ram`), the cycle counters (`s_pc`, `s_cycles`, `s_remaining_cycles`) and
/// the access helpers (`peek`, `poke`, `ram_peek16al`, `push8`, `pop8`,
/// `push16`, `pop16`, ...) are all `static`. The `CYCLES()` macro expands to
/// references to those statics plus the caller's local `branchTarget`.
///
/// `apple2tc/system.h` exports only `ram_peek`/`ram_poke`/`ram_peek16`,
/// `io_peek`/`io_poke` and `error_handler`, which is nowhere near enough to
/// implement a 6502 routine. On top of that, `a2rom.c` calls the generated
/// helpers `FUNC_VTABZ`, `FUNC_CLREOLZ`, `FUNC_CLREOL` and `FUNC_MON_WAIT` and
/// uses the generated `static` helpers `ovf8()` and `adc_dec16()`.
///
/// So `a2rom.c` cannot be a separate object file; it has to share a translation
/// unit with the generated code.
///
/// Include order matters
/// ---------------------
/// `snake-byte-easyc1-ext.c` must come first: it pulls in `system2-inc.h` and
/// defines the statics and helper functions that `a2rom.c` depends on. Swapping
/// the two lines produces a wall of undefined identifiers.

/* Renamed so this file can wrap it -- see init_emulated() at the bottom. */
#define init_emulated snake_byte_generated_init_emulated
#include "snake-byte-easyc1-ext.c"
#undef init_emulated
#include "a2rom.c"
#include "game.c" /* after a2rom.c: uses its static rom_cout1() */

/// Why init_emulated() is wrapped
/// ------------------------------
/// The decompilation traces from the reset vector, so it reproduces the whole
/// boot and comes up at the Applesoft prompt -- exactly as the machine did.
/// The recorded session started the game from there by typing `CALL 14160`
/// ($3750, the load address), which is why play.keys opens with those
/// keystrokes and why play.kbd exists. Run the built program with no input and
/// you get the prompt and nothing else.
///
/// So the program types it for itself. a2host_buffer_keys() queues keystrokes
/// the same way --kbd-file feeds a file, and a2host_init_emulation() drains
/// them right after calling init_emulated() -- which is the only startup hook
/// a program gets, since apple2tc generates that function rather than the host
/// or this file defining it. Hence the rename on the #include above: the
/// generated body runs first, then the keys go in.
///
/// Both --key-file and --kbd-file take precedence inside a2host, so every
/// replay -- verify.sh, probe-acceptance.sh -- is untouched. Those recordings
/// already contain the CALL.
///
/// The real fix is to retarget the entry point to $3750 and skip the boot
/// entirely (step 4b in docs/decompiling/playbook.md). That needs an
/// entry-state snapshot, because a cold start skips the frames every golden
/// trace opens with, and no --snapshot-at exists yet. This is the stopgap.
void init_emulated(void);

void init_emulated(void) {
  snake_byte_generated_init_emulated();
  a2host_buffer_keys("call 14160\n");
}
