# Copyright (c) Tzvetan Mikov.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

add_subdirectory(id)
add_subdirectory(textemu)
add_subdirectory(a2emu)
add_subdirectory(a2run)
add_subdirectory(a2mcp)
add_subdirectory(a6502)
add_subdirectory(apple2tc)
